### ISSUE TITLE
setMarkerDrawable method didn't work

### ISSUE THREAD

**Issue by samSpark** [qiujuer/BeFoot#1]
setMarkerDrawable设置图片drawable为什么会无效呢？

**Comment by qiujuer** [comment]
你好，方便看看你的具体代码么？

**Comment by samSpark** [comment]
哈哈是有效的o(^▽^)o

**Comment by LomoLin** [comment]
在TimeLineMarker中的initDrawableSize中，
int markerSize = Math.min(mMarkerSize, Math.min(cWidth, cHeight));
也就是markerSize会随着每个item的（不一样的）高度而变化，这就会导致timeline会错开，
请验证下该问题。
应该让markerSize不变，保持为mMarkerSize。
